// AUTO-GENERATED by scripts/gen-tier-icons.mjs — 직접 수정 금지
export type TierEntry = { id: string; name: string; group: string; icon: string };

export const TIER_ENTRIES: TierEntry[] = [
  {
    "id": "가나 드드",
    "name": "가나 드드",
    "group": "전사",
    "icon": "/class-icons/%EA%B0%80%EB%82%98%20%EB%93%9C%EB%93%9C.webp"
  },
  {
    "id": "가나 업화",
    "name": "가나 업화",
    "group": "전사",
    "icon": "/class-icons/%EA%B0%80%EB%82%98%20%EC%97%85%ED%99%94.webp"
  },
  {
    "id": "디트 분망",
    "name": "디트 분망",
    "group": "전사",
    "icon": "/class-icons/%EB%94%94%ED%8A%B8%20%EB%B6%84%EB%A7%9D.webp"
  },
  {
    "id": "디트 중수",
    "name": "디트 중수",
    "group": "전사",
    "icon": "/class-icons/%EB%94%94%ED%8A%B8%20%EC%A4%91%EC%88%98.webp"
  },
  {
    "id": "발키리 빛의기사",
    "name": "발키리 빛의기사",
    "group": "전사",
    "icon": "/class-icons/%EB%B0%9C%ED%82%A4%EB%A6%AC%20%EB%B9%9B%EC%9D%98%EA%B8%B0%EC%82%AC.webp"
  },
  {
    "id": "발키리 해방자",
    "name": "발키리 해방자",
    "group": "전사",
    "icon": "/class-icons/%EB%B0%9C%ED%82%A4%EB%A6%AC%20%ED%95%B4%EB%B0%A9%EC%9E%90.webp"
  },
  {
    "id": "버서커 광기",
    "name": "버서커 광기",
    "group": "전사",
    "icon": "/class-icons/%EB%B2%84%EC%84%9C%EC%BB%A4%20%EA%B4%91%EA%B8%B0.webp"
  },
  {
    "id": "버서커 비기",
    "name": "버서커 비기",
    "group": "전사",
    "icon": "/class-icons/%EB%B2%84%EC%84%9C%EC%BB%A4%20%EB%B9%84%EA%B8%B0.webp"
  },
  {
    "id": "슬레 처단",
    "name": "슬레 처단",
    "group": "전사",
    "icon": "/class-icons/%EC%8A%AC%EB%A0%88%20%EC%B2%98%EB%8B%A8.webp"
  },
  {
    "id": "슬레 포식",
    "name": "슬레 포식",
    "group": "전사",
    "icon": "/class-icons/%EC%8A%AC%EB%A0%88%20%ED%8F%AC%EC%8B%9D.webp"
  },
  {
    "id": "워로드 고기",
    "name": "워로드 고기",
    "group": "전사",
    "icon": "/class-icons/%EC%9B%8C%EB%A1%9C%EB%93%9C%20%EA%B3%A0%EA%B8%B0.webp"
  },
  {
    "id": "워로드 전태",
    "name": "워로드 전태",
    "group": "전사",
    "icon": "/class-icons/%EC%9B%8C%EB%A1%9C%EB%93%9C%20%EC%A0%84%ED%83%9C.webp"
  },
  {
    "id": "홀나 심판자",
    "name": "홀나 심판자",
    "group": "전사",
    "icon": "/class-icons/%ED%99%80%EB%82%98%20%EC%8B%AC%ED%8C%90%EC%9E%90.webp"
  },
  {
    "id": "홀나 축오",
    "name": "홀나 축오",
    "group": "전사",
    "icon": "/class-icons/%ED%99%80%EB%82%98%20%EC%B6%95%EC%98%A4.webp"
  },
  {
    "id": "기공 세맥",
    "name": "기공 세맥",
    "group": "무도가",
    "icon": "/class-icons/%EA%B8%B0%EA%B3%B5%20%EC%84%B8%EB%A7%A5.webp"
  },
  {
    "id": "기공 역천",
    "name": "기공 역천",
    "group": "무도가",
    "icon": "/class-icons/%EA%B8%B0%EA%B3%B5%20%EC%97%AD%EC%B2%9C.webp"
  },
  {
    "id": "배마 오의",
    "name": "배마 오의",
    "group": "무도가",
    "icon": "/class-icons/%EB%B0%B0%EB%A7%88%20%EC%98%A4%EC%9D%98.webp"
  },
  {
    "id": "배마 초심",
    "name": "배마 초심",
    "group": "무도가",
    "icon": "/class-icons/%EB%B0%B0%EB%A7%88%20%EC%B4%88%EC%8B%AC.webp"
  },
  {
    "id": "브커 권왕",
    "name": "브커 권왕",
    "group": "무도가",
    "icon": "/class-icons/%EB%B8%8C%EC%BB%A4%20%EA%B6%8C%EC%99%95.webp"
  },
  {
    "id": "브커 수라",
    "name": "브커 수라",
    "group": "무도가",
    "icon": "/class-icons/%EB%B8%8C%EC%BB%A4%20%EC%88%98%EB%9D%BC.webp"
  },
  {
    "id": "스커 난무",
    "name": "스커 난무",
    "group": "무도가",
    "icon": "/class-icons/%EC%8A%A4%EC%BB%A4%20%EB%82%9C%EB%AC%B4.webp"
  },
  {
    "id": "스커 일격",
    "name": "스커 일격",
    "group": "무도가",
    "icon": "/class-icons/%EC%8A%A4%EC%BB%A4%20%EC%9D%BC%EA%B2%A9.webp"
  },
  {
    "id": "인파 체술",
    "name": "인파 체술",
    "group": "무도가",
    "icon": "/class-icons/%EC%9D%B8%ED%8C%8C%20%EC%B2%B4%EC%88%A0.webp"
  },
  {
    "id": "인파 충단",
    "name": "인파 충단",
    "group": "무도가",
    "icon": "/class-icons/%EC%9D%B8%ED%8C%8C%20%EC%B6%A9%EB%8B%A8.webp"
  },
  {
    "id": "창술 절정",
    "name": "창술 절정",
    "group": "무도가",
    "icon": "/class-icons/%EC%B0%BD%EC%88%A0%20%EC%A0%88%EC%A0%95.webp"
  },
  {
    "id": "창술 절제",
    "name": "창술 절제",
    "group": "무도가",
    "icon": "/class-icons/%EC%B0%BD%EC%88%A0%20%EC%A0%88%EC%A0%9C.webp"
  },
  {
    "id": "건슬 사시",
    "name": "건슬 사시",
    "group": "헌터",
    "icon": "/class-icons/%EA%B1%B4%EC%8A%AC%20%EC%82%AC%EC%8B%9C.webp"
  },
  {
    "id": "건슬 피메",
    "name": "건슬 피메",
    "group": "헌터",
    "icon": "/class-icons/%EA%B1%B4%EC%8A%AC%20%ED%94%BC%EB%A9%94.webp"
  },
  {
    "id": "데헌 전탄",
    "name": "데헌 전탄",
    "group": "헌터",
    "icon": "/class-icons/%EB%8D%B0%ED%97%8C%20%EC%A0%84%ED%83%84.webp"
  },
  {
    "id": "데헌 핸건",
    "name": "데헌 핸건",
    "group": "헌터",
    "icon": "/class-icons/%EB%8D%B0%ED%97%8C%20%ED%95%B8%EA%B1%B4.webp"
  },
  {
    "id": "블래 포강",
    "name": "블래 포강",
    "group": "헌터",
    "icon": "/class-icons/%EB%B8%94%EB%9E%98%20%ED%8F%AC%EA%B0%95.webp"
  },
  {
    "id": "블래 화강",
    "name": "블래 화강",
    "group": "헌터",
    "icon": "/class-icons/%EB%B8%94%EB%9E%98%20%ED%99%94%EA%B0%95.webp"
  },
  {
    "id": "스카 기술",
    "name": "스카 기술",
    "group": "헌터",
    "icon": "/class-icons/%EC%8A%A4%EC%B9%B4%20%EA%B8%B0%EC%88%A0.webp"
  },
  {
    "id": "스카 유산",
    "name": "스카 유산",
    "group": "헌터",
    "icon": "/class-icons/%EC%8A%A4%EC%B9%B4%20%EC%9C%A0%EC%82%B0.webp"
  },
  {
    "id": "호크 두동",
    "name": "호크 두동",
    "group": "헌터",
    "icon": "/class-icons/%ED%98%B8%ED%81%AC%20%EB%91%90%EB%8F%99.webp"
  },
  {
    "id": "호크 죽습",
    "name": "호크 죽습",
    "group": "헌터",
    "icon": "/class-icons/%ED%98%B8%ED%81%AC%20%EC%A3%BD%EC%8A%B5.webp"
  },
  {
    "id": "바드 절구",
    "name": "바드 절구",
    "group": "마법사",
    "icon": "/class-icons/%EB%B0%94%EB%93%9C%20%EC%A0%88%EA%B5%AC.webp"
  },
  {
    "id": "바드 진용",
    "name": "바드 진용",
    "group": "마법사",
    "icon": "/class-icons/%EB%B0%94%EB%93%9C%20%EC%A7%84%EC%9A%A9.webp"
  },
  {
    "id": "서머너 교감",
    "name": "서머너 교감",
    "group": "마법사",
    "icon": "/class-icons/%EC%84%9C%EB%A8%B8%EB%84%88%20%EA%B5%90%EA%B0%90.webp"
  },
  {
    "id": "서머너 상소",
    "name": "서머너 상소",
    "group": "마법사",
    "icon": "/class-icons/%EC%84%9C%EB%A8%B8%EB%84%88%20%EC%83%81%EC%86%8C.webp"
  },
  {
    "id": "소서 점화",
    "name": "소서 점화",
    "group": "마법사",
    "icon": "/class-icons/%EC%86%8C%EC%84%9C%20%EC%A0%90%ED%99%94.webp"
  },
  {
    "id": "소서 환류",
    "name": "소서 환류",
    "group": "마법사",
    "icon": "/class-icons/%EC%86%8C%EC%84%9C%20%ED%99%98%EB%A5%98.webp"
  },
  {
    "id": "알카 황제",
    "name": "알카 황제",
    "group": "마법사",
    "icon": "/class-icons/%EC%95%8C%EC%B9%B4%20%ED%99%A9%EC%A0%9C.webp"
  },
  {
    "id": "알카 황후",
    "name": "알카 황후",
    "group": "마법사",
    "icon": "/class-icons/%EC%95%8C%EC%B9%B4%20%ED%99%A9%ED%9B%84.webp"
  },
  {
    "id": "데모닉 억제",
    "name": "데모닉 억제",
    "group": "암살자",
    "icon": "/class-icons/%EB%8D%B0%EB%AA%A8%EB%8B%89%20%EC%96%B5%EC%A0%9C.webp"
  },
  {
    "id": "데모닉 충동",
    "name": "데모닉 충동",
    "group": "암살자",
    "icon": "/class-icons/%EB%8D%B0%EB%AA%A8%EB%8B%89%20%EC%B6%A9%EB%8F%99.webp"
  },
  {
    "id": "리퍼 갈증",
    "name": "리퍼 갈증",
    "group": "암살자",
    "icon": "/class-icons/%EB%A6%AC%ED%8D%BC%20%EA%B0%88%EC%A6%9D.webp"
  },
  {
    "id": "리퍼 달소",
    "name": "리퍼 달소",
    "group": "암살자",
    "icon": "/class-icons/%EB%A6%AC%ED%8D%BC%20%EB%8B%AC%EC%86%8C.webp"
  },
  {
    "id": "블레 버스트",
    "name": "블레 버스트",
    "group": "암살자",
    "icon": "/class-icons/%EB%B8%94%EB%A0%88%20%EB%B2%84%EC%8A%A4%ED%8A%B8.webp"
  },
  {
    "id": "블레 잔재",
    "name": "블레 잔재",
    "group": "암살자",
    "icon": "/class-icons/%EB%B8%94%EB%A0%88%20%EC%9E%94%EC%9E%AC.webp"
  },
  {
    "id": "소울 그믐",
    "name": "소울 그믐",
    "group": "암살자",
    "icon": "/class-icons/%EC%86%8C%EC%9A%B8%20%EA%B7%B8%EB%AF%90.webp"
  },
  {
    "id": "소울 만월",
    "name": "소울 만월",
    "group": "암살자",
    "icon": "/class-icons/%EC%86%8C%EC%9A%B8%20%EB%A7%8C%EC%9B%94.webp"
  },
  {
    "id": "기상 이슬비",
    "name": "기상 이슬비",
    "group": "스페셜리스트",
    "icon": "/class-icons/%EA%B8%B0%EC%83%81%20%EC%9D%B4%EC%8A%AC%EB%B9%84.webp"
  },
  {
    "id": "기상 질풍",
    "name": "기상 질풍",
    "group": "스페셜리스트",
    "icon": "/class-icons/%EA%B8%B0%EC%83%81%20%EC%A7%88%ED%92%8D.webp"
  },
  {
    "id": "도화가 만개",
    "name": "도화가 만개",
    "group": "스페셜리스트",
    "icon": "/class-icons/%EB%8F%84%ED%99%94%EA%B0%80%20%EB%A7%8C%EA%B0%9C.webp"
  },
  {
    "id": "도화가 회귀",
    "name": "도화가 회귀",
    "group": "스페셜리스트",
    "icon": "/class-icons/%EB%8F%84%ED%99%94%EA%B0%80%20%ED%9A%8C%EA%B7%80.webp"
  },
  {
    "id": "환수 각성",
    "name": "환수 각성",
    "group": "스페셜리스트",
    "icon": "/class-icons/%ED%99%98%EC%88%98%20%EA%B0%81%EC%84%B1.webp"
  },
  {
    "id": "환수 야성",
    "name": "환수 야성",
    "group": "스페셜리스트",
    "icon": "/class-icons/%ED%99%98%EC%88%98%20%EC%95%BC%EC%84%B1.webp"
  }
];
